# You can specify a custom docker image from Docker Hub as your build environment.
image: node:6.9.4

# Doing a full clone to be able to push back to Heroku.
clone:
  depth: full

pipelines:
  branches:
    develop:
     - step:
        name: Deploy to test
        deployment: test
        script: # Modify the commands below to build your repository.
             - npm install
             - git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_TEST.git HEAD:master
    master:
     - step:
        name: Deploy to test
        deployment: test
        script: # Modify the commands below to build your repository.
             - npm install
             - git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_TEST.git HEAD:master
